- hosts: localhost
  pre_tasks:
    - name: Update apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core
  tasks:
    - import_tasks: tasks/docker.yml
    - import_tasks: tasks/neovim.yml
    - import_tasks: tasks/python.yml
    - import_tasks: tasks/utilities.yml
