- name: Go tasks
  tags: go
  vars:
    go_location: /usr/local
  block:
    - name: Remove old go install
      become: true
      file:
        path: "{{ go_location }}/go"
        state: absent

    - name: Unzip to go location
      become: true
      unarchive:
        src: https://go.dev/dl/go1.19.linux-amd64.tar.gz
        dest: "{{ go_location }}"
        remote_src: true

    - name: Install gopls
      shell: "GOBIN=${HOME}/bin go install golang.org/x/tools/gopls@latest"
