- name: Install neovim
  tags:
    - neovim
  vars:
    neovim_location: "{{ lookup('env', 'HOME') }}/opt/neovim"
    luals_location: "{{ lookup('env', 'HOME') }}/opt/lua-language-server"
  block:
    - name: Build prerequisites
      become: true
      apt:
        name:
          [
            "ninja-build",
            "gettext",
            "cmake",
            "unzip",
            "curl",
            "build-essential",
          ]

    - name: Clone neovim
      git:
        repo: git@github.com:neovim/neovim
        dest: "{{ neovim_location }}"
        force: true
        version: stable
      register: gitclone

    - name: Build neovim
      shell:
        chdir: "{{ neovim_location }}"
        cmd: "make CMAKE_BUILD_TYPE=Release"
      when: gitclone.changed

    - name: Install neovim
      become: true
      shell:
        chdir: "{{ neovim_location }}"
        cmd: "make install"
      when: gitclone.changed

    - name: Clone lua-language-server
      git:
        repo: git@github.com:LuaLS/lua-language-server
        dest: "{{ luals_location }}"
        force: true
      register: gitclone2

    - name: Build lua-language-server
      become: true
      shell:
        chdir: "{{ luals_location }}"
        cmd: "./make.sh"
      when: gitclone2.changed

    - name: Create ~/bin
      file:
        path: "{{ lookup('env', 'HOME') }}/bin"
        state: directory

    - name: Symlink lua-language-server
      file:
        src: "{{ luals_location }}/bin/lua-language-server"
        dest: "{{ lookup('env', 'HOME') }}/bin/lua-language-server"
        state: link
