- name: Node tasks
  tags: node
  vars:
    global_location: "{{ lookup('env', 'HOME') }}/.npm-global"
  block:
    - name: Install nodejs and npm
      become: true
      apt:
        name: ["nodejs", "npm"]

    - name: Create directory for global npm and yarn packages
      file:
        path: "{{ global_location }}"
        state: directory
        mode: "0755"

    - name: Set npm to use directory # noqa no-changed-when
      shell: "npm config set prefix {{ global_location }}"

    - name: Install N
      npm:
        name: n
        global: true

    - name: Install correct version of Node # noqa no-changed-when
      become: true
      shell: "{{ global_location }}/bin/n lts"

    - name: Install node packages
      npm:
        name: "{{ item }}"
        global: true
      loop:
        - "@ansible/ansible-language-server"
        - eslint
        - neovim
        - prettier
        - ts-node
        - typescript
        - "@tailwindcss/language-server"
        - typescript-language-server
        - vscode-langservers-extracted
