- name: Python tasks
  tags: python
  block:
  - name: Install required system packages
    become: true
    apt:
      name: ['ca-certificates', 'curl']

  - name: Install python system packages
    become: true
    apt:
      name: ['python3-dev', 'python3-distutils']
  
  - name: Add deadsnakes repository
    become: true
    apt_repository:
      repo: ppa:deadsnakes/ppa
      state: present
      update_cache: true
  
  - name: Install python versions
    become: true
    apt:
      name: ['python3.8-dev', 'python3.8-distutils', 'python3.9-dev', 'python3.9-distutils', 'python3.11-dev', 'python3.11-distutils']
