- name: Utilities
  tags: core
  become: true
  apt:
    name:
      [
        "clangd-14",
        "curl",
        "eza",
        "neofetch",
        "ninja-build",
        "fd-find",
        "fish",
        "fonts-powerline",
        "lldb-18",
        "ripgrep",
        "sqlite3",
        "stow",
        "tmux",
        "tree",
        "xclip",
      ]

- name: Symlink fdfind to fd
  file:
    src: "/usr/bin/fdfind"
    dest: "{{ lookup('env', 'HOME') }}/bin/fd"
    state: link
